### ISSUE TITLE
Error with function 'get_phrdw_data'

### ISSUE THREAD

**Issue by B-Klaver** [mikuo0628/phrdwRdata#1]
When calling:
`phrdwRdata::get_phrdw_data(
  mart = 'cdi',
  dataset_name = 'vital stats ccd dashboard',
  query_start_date = "2009-01-01",
  query_end_date = as.character(Sys.Date())
)`

Error returned:
` Error: 'OlapConnection' is not an exported object from 'namespace:phrdwRdata' `

Appears to be due to missing export call for the function 'OlapConnection'.

**Comment by mikuo0628** [comment]
Fixed in commit 3ee34788ac2f3fe506f73921a0900d439b30cf9e.
